<MyGrid>
    GridLayout:
        cols:1
        size: root.width, root.height

        GridLayout:
            cols:2

            Label:
                text: "First Name: "

            TextInput:
                multiline:False

            Label:
                text: "Last Name: "

            TextInput:
                multinline:False

            Label:
                text: "Email: "

            TextInput:
                multinline:False

        Button:
            text: "Submit"